version: '2.1.{build}-win'
clone_folder: c:\src
install:
  - ps: (new-object net.webclient).DownloadFile('https://www.libsdl.org/release/SDL2-2.0.5.zip', 'SDL2-2.0.5.zip')
  - ps: 7z x SDL2-2.0.5.zip

before_build:
  - nuget restore

platform:
  - x86
  - Any CPU

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

  
