version: '2.1.{build}-win'
clone_folder: c:\src
install:
  # Install Eigen
  cd c:\src\lib
  - ps: Start-FileDownload 'http://bitbucket.org/eigen/eigen/get/3.2.10.zip' -FileName 'eigen-3.2.10.zip'
  #- 7z x eigen-3.2.10.zip > NUL
  # Install SDL2
  #- ps: Start-FileDownload 'https://www.libsdl.org/release/SDL2-2.0.5.zip' -FileName 'SDL2-2.0.5.zip'
  #- 7z x SDL2-2.0.5.zip > NUL
  # Install FreeImage
  #- ps: Start-FileDownload 'http://downloads.sourceforge.net/freeimage/FreeImage3170.zip' -FileName 'FreeImage3170.zip'
  #- 7z x FreeImage3170.zip > NUL
  # Install Free
  #- ps: Start-FileDownload 'http://download.savannah.gnu.org/releases/freetype/freetype-2.7.tar.gz' -FileName 'freetype-2.7.tar.gz'
  #- 7z x freetype-2.7.tar.gz 
before_build:
  - nuget restore

platform:
  - x86
  - Any CPU

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

  
